### ISSUE TITLE
No Nodemcu .bin file in since 1.4 release

### ISSUE THREAD

**Issue by wsfuller** [acrobotic/Ai_Tips_ESP8266#2]
So I'm going through the [tutorial](http://learn.acrobotic.com/tutorials/post/esp8266-getting-started) since the video skips way ahead of someone who is starting out. 

One of the steps for **Flashing the firmware to the ESP8266** `python esptool.py --port /dev/tty.SLAB_USBtoUART write_flash 0x00000 ~/Downloads/nodemcu_float_0.9.6-dev_20150704.bin
`

Problem is the, there is no `.bin` file in the latest release 
<img width="1024" alt="screen shot 2017-06-11 at 9 42 29 pm" src="https://user-images.githubusercontent.com/3144419/27019610-e674b956-4eee-11e7-998c-1a1c21e2debd.png">

However in the example in the tutorial:

<img width="1034" alt="screen shot 2017-06-11 at 9 43 20 pm" src="https://user-images.githubusercontent.com/3144419/27019621-02cd5d24-4eef-11e7-9f4a-54928bb01f40.png">

You can see there is a `.bin` file available.

**Comment by datasith** [comment]
You're absolutely right, **[binaries are no longer released](https://github.com/nodemcu/nodemcu-firmware/releases/tag/1.4.0-master_20151229)** so we need to update the tutorial, and make an additional one for showing how to compile the source and generate them!

![screen shot 2017-06-11 at 11 34 51 pm](https://user-images.githubusercontent.com/7302561/27021623-88107732-4efe-11e7-9e69-fd1b72a8ab2f.png)

**Comment by wsfuller** [comment]
Also wanted to mention I'm going through this all for the first time and haven't done anything with Python before so didn't have any libraries installed. Going through the guide been making notes with all the errors that and such I've been running into. Is there any sort of guide for environment setup? I took a bunch of notes and can contribute my experience. But thought if the tutorial gets updated might be a nice to have if it hasn't been made already.

**Comment by datasith** [comment]
We'll update the tutorial in the near future, thanks for the offer to chip in!
